name: Update arXiv Paper Daily

on:
  schedule:
    - cron: '0 1,2,3,4,7,10 * * *'  # 北京时间 09,10,11,12,15,18 点
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script with today's date
        run: python get_daily_arxiv_paper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update arXiv paper for $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"
          git push