name: Update arXiv Paper Daily

on:
  schedule:
    - cron: '0 2 * * *'  # UTC 02:00 = UTC+8 10:00
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script with today's date
        run: python get_daily_arxiv_paper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update arXiv paper for $(date -d 'yesterday' +%Y-%m-%d)" && git push)